


Page({
  data:{
    systemMenuList:[
      {
        title:'账号管理',
        path:'/pages/acount/index',
        icon:'user-o'
      },
      {
        title:'权限管理',
        path:'/pages/auth/index',
        icon:'shield-o'
      },
      {
        title:'角色管理',
        path:'/pages/role/index',
        icon:'manager-o'
      },
    ],
    colNum:4,
    treeData:[
      {
        title:'1',
        children:[
          {
            title:'1-1',
            children:[
              {
                title:'1-1-1'
              },
              {
                title:'1-1-2'
              },
            ]
          },
          {
            title:'1-2'
          },
        ]
      },
      {
        title:'2',
        children:[
          {
            title:'2-1'
          },
          {
            title:'2-2'
          },
        ]
      }
    ]
  },

})